name: zig
title: Zig
summary: Zig Programming Language
description: Zig is a general-purpose programming language and toolchain for
  maintaining robust, optimal, and reusable software.
license: MIT

base: bare
build-base: core20
confinement: classic
grade: devel
version: master
version-script: $SNAPCRAFT_PRIME/zig version

apps:
  zig:
    command: zig

parts:
  zig:
    plugin: dump
    source: https://ziglang.org/builds/zig-linux-x86_64-$SNAPCRAFT_PROJECT_VERSION.tar.xz
