#!/bin/sh -e
#
# Snaphack is a hacky script for creating simple snaps.
#
# Usage: snaphack.sh <zig version> <arch> <tarball url>

export SNAPHACK_PROJECT_VERSION=$1
export SNAPHACK_ARCH=$2
tarball=$3

# Create staging directory.
staging_dir=$(mktemp --directory snaphack-XXXXX)
echo $staging_dir

# Extract tarball of build to staging directory.
curl --silent $tarball | tar --extract --one-top-level=$staging_dir --strip-components=1 --xz

# Add metadata.
mkdir --parents $staging_dir/meta
envsubst < snap.yaml > $staging_dir/meta/snap.yaml

# Create the snap.
snap pack $staging_dir

# Cleanup.
rm -rf $staging_dir
