name: zig
version: git
version-script: prime/zig version
summary: Zig Programming Language
description: Zig is an open-source programming language designed for robustness, optimality, and clarity.
grade: devel
confinement: classic

apps:
  zig:
    command: zig

parts:
  zig:
    plugin: dump
    source: https://ziglang.org/builds/zig-linux-x86_64-master.tar.xz
