#!/bin/sh -e
#
# Snaphack is a hacky script for creating simple snaps.
#
# Usage: snaphack.sh <zig version> <arch> <tarball url>
#
# TODO: Check out tar2sqfs once squashfs-tools-ng appears in the package manager.

export SNAPHACK_PROJECT_VERSION=$1
export SNAPHACK_ARCH=$2
tarball=$3
snap_build=zig_${SNAPHACK_PROJECT_VERSION}_${SNAPHACK_ARCH}
staging_dir=$(mktemp --directory snaphack-XXXXX)
echo $staging_dir

# Extract tarball of build to staging directory.
curl --silent $tarball | tar --extract --one-top-level=$staging_dir --strip-components=1 --xz

# Add metadata.
mkdir --parents $staging_dir/meta
envsubst < snap.yaml > $staging_dir/meta/snap.yaml

# Create the snap.
mksquashfs $staging_dir $snap_build.snap -noappend -comp xz -no-xattrs -no-fragments -all-root

rm -rf $staging_dir

echo $snap_build.snap
