name: zig
title: Zig
summary: Zig Programming Language
description: Zig is an open-source programming language designed for robustness, optimality, and maintainability.
license: MIT

base: core18
confinement: classic
grade: devel
version: master
version-script: $SNAPCRAFT_PRIME/zig version

apps:
  zig:
    command: zig

parts:
  zig:
    plugin: dump
    source: https://ziglang.org/builds/zig-linux-x86_64-$SNAPCRAFT_PROJECT_VERSION.tar.xz
